@startuml OWL

title OWL Architecture

class DatabaseConnection {
    + readonly string connectionString
    + DatabaseConnection(connectionString)

    + void StartConnection()
}

' class GamemodeDto {
'     + string Name
'     + string Description
'     + int Amount_players
' }

' class GamemodeService {
'     + GamemodeService()
'     + void Gamemode()
'     + string CreateGamemode()
'     + string GetGamemodes()
'     + string AddToGamemode()
' }

Class CharacterController {
    - readonly CharacterService

    + CharacterController
    + Index()
}

Interface ICharacterRepository {
    +  List<CharacterDto> GetAllCharacters();
}

Class CharacterRepository {
    +  CharacterRepository(DatabaseConnection)
    +  List<CharacterDto> GetAllCharacters()
    -  CharacterDto MapCharacterDtoFromReader(SqlDataReader reader)
}

class Character {
    + string Name
    + string Description
    + string Image
    + bool Newly_added
}

class CharacterDto {
    + string Name
    + string Description
    + string Image
    + bool Newly_added
}

class CharacterService {
    - readonly ICharacterRepository

    + CharacterService(IcharacterRepository)
    + string CreateCharacter()
    + List<Character> GetAllCharacters()
    + string UpdateCharacter()
    + bool DetectNewlyAdded()
}

' class FightstyleDto {
'     + string Name
'     + int Power
'     + int Speed
' }

' class FightstyleService {

'     + FightstyleService()
'     + string GetStyles()
'     + string CreateStyle()
'     + string UpdateStyle()
'     + string AddStyleToChar()
' }

' class MoveDto {
'     + string Name
'     + string Description
'     + string Image
'     + string Motion
' }

' class MoveService {

'     + MoveService()
'     + string GetMoves()
'     + string CreateMove()
'     + string UpdateMove()
'     + string AddMoveToChar()
' }

' class NewsDto {
'     + string Title
'     + string Description
'     + string Image
' }

' class NewsService {

'     + NewsService()
'     + string GetArticles()
'     + string CreateArticle()
' }

' class CategoryDto {
'     + string Name
' }

' class CategoryService {
'     + CategoryService()
'     + string GetCategories()
' }

DatabaseConnection <-- CharacterRepository

CharacterController --> CharacterService
Character <-- CharacterService
CharacterController --> Character
CharacterService ..> CharacterDto
CharacterService --> ICharacterRepository
CharacterDto ..> ICharacterRepository
ICharacterRepository --> CharacterRepository

' NewsService <-- NewsDto
' CategoryService <-- CategoryDto
' FightstyleService <-- FightstyleDto
' MoveService <-- MoveDto
' GamemodeService <-- GamemodeDto

@enduml