@startuml OWL

title OWL

class Gamemode {
    + string Name
    + string Description
    + int Amount_players

    + void Gamemode()
    + string CreateGamemode()
    + string GetGamemodes()
    + string AddToGamemode()
}


class Character {
    + string Name
    + string Description
    + string Image
    + bool Newly_added

    + void Character()
    + string CreateCharacter()
    + string GetCharacters()
    + string UpdateCharacter()
    + bool DetectNewlyAdded()
}

Interface ICharacter {
    + string Name
    + string Description
    + string Image
    + bool Newly_added

    + string CreateCharacter()
    + string GetCharacters()
    + string UpdateCharacter()
    + bool DetectNewlyAdded()
}

class Fightstyle {
    + string Name
    + int Power
    + int Speed

    + string GetStyles()
    + string CreateStyle()
    + string UpdateStyle()
    + string AddStyleToChar()
}

class Move {
    + string Name
    + string Description
    + string Image
    + string Motion

    + string GetMoves()
    + string CreateMove()
    + string UpdateMove()
    + string AddMoveToChar()
}

class News {
    + string Title
    + string Description
    + string Image
    + Enum Category

    + string GetArticles()
    + string CreateArticle()
}

enum Category {
    Updates
    Characters
    Merchandise
    Events
}

Character <|-- "<List>Move *" Move
Character <|-- "Fightstyle 1" Fightstyle
News --* "1" Category
Gamemode <|-- "<List>Character *" Character
ICharacter <|--  Character

@enduml